apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taslak-redis
  namespace: taslak
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: taslak-redis