apiVersion: v1
kind: Service
metadata:
  name: taslak-redis
  namespace: taslak
spec:
  selector:
    app: taslak-redis
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30001