apiVersion: v1
kind: PersistentVolume
metadata:
   name: taslak-redis
   labels:
     app: taslak-redis
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/taslak-redis